services:
  - type: web
    name: hodlem-sol
    env: node
    buildCommand: npm install && npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://hodlem-sol.onrender.com

  - type: web
    name: hodlem-sol-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://hodlem-sol-backend.onrender.com 