services:
  - type: web
    name: hodlem-sol
    env: node
    buildCommand: |
      echo "Starting build process..."
      npm install
      echo "Building client..."
      cd client && npm install && npm run build
      cd ..
      echo "Building server..."
      npm run build
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Client directory contents:"
      ls -la client
      echo "Client build directory contents:"
      ls -la client/build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CLIENT_URL
        value: https://hodlem-sol.onrender.com 